### ISSUE TITLE
Suspicious warning 'reserveCache failed' in Post Cache

### ISSUE THREAD

**Issue by sideeffffect** [coursier/cache-action#102]
We're using `coursier/cache-action@v5`: https://github.com/zio/zio-telemetry/blob/master/.github/workflows/ci.yml#L46

In the `Post Cache scala dependencies` step, we're seeing suspicious warnings:
```
Post job cleanup.
Saving coursier cache
Warning:  reserveCache failed: Cache already exists. Scope: refs/heads/master, Key: Linux-coursier-3079bd8f16e7a25e57b7c35b9b13090eb7092b1f, Version: 1e08b80f3462916ac2d5654f6b399c900980cc0f9b928b367a6df70ad7ddd959
Saving sbt-ivy2-cache cache
Warning:  reserveCache failed: Cache already exists. Scope: refs/heads/master, Key: Linux-sbt-ivy2-cache-91f8e0fa8ca1f9c6c77811374a8bcb945b2387c8, Version: 9635c9698008b57d9157eed8e70fa13373c2bf90a51d9edde39fe4b528f54439
```
https://github.com/zio/zio-telemetry/runs/1797302607?check_suite_focus=true#step:9:3

Is this an expected behavior? The fact that it's a warning makes us not 100% sure that we're using `coursier/cache-action` correctly.

/cc @mijicd

**Comment by alexarchambault** [comment]
The new `v6` release should fix that. It deals better out-of-the-box with job names and matrices, that I think are the problem here.

**Comment by alexarchambault** [comment]
Closing this, this should work fine with `v6`.
