### ISSUE TITLE
Consider moving major tags after releases

### ISSUE THREAD

**Issue by giarc3** [coursier/cache-action#280]
According to the GitHub Actions toolkit versioning recommendations (https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations), major version tags should be moved to point to the ref of the current release. This would allow anyone binding to v6 to get the latest fixes, while others could bind to something like `6.1` if they need a specific commit.
For this repo, this would also require what is currently `v6` to be renamed to `v6.0` so that `v6` can move to the latest version.

**Comment by ihostage** [comment]
☝️@alexarchambault Can you force re-push `v6` tag to latest `v6.3.1`? Please 🙏

**Comment by mkurz** [comment]
+1 please force push the tag! Thanks!
