### ISSUE TITLE
Post run action takes too much time occasionally

### ISSUE THREAD

**Issue by davidak09** [coursier/cache-action#580]
Some runs of post run action for coursier/cache-action@v6 take minutes to finish. The behavior is flipping, other runs are done under one second. We're using proprietary runners.

<img width="2164" alt="Screenshot 2024-03-05 at 16 51 37" src="https://github.com/coursier/cache-action/assets/3399761/29311939-a2c8-4cf9-99ff-f5d54947c0b3">

Could you please guess what might be the cause of this slow step?

**Comment by laughedelic** [comment]
I have been observing this for a while as well. If you flip the timestamps in the logs, you can see that it gets stuck after saving all the cache for ~3m:
![Screenshot 2024-03-20 at 17 35 25](https://github.com/coursier/cache-action/assets/766656/3109750d-c598-4dfa-9f11-fc47b8042d97)

What could be the reason for this?
